--DROP TABLE TASK_MANAGER IF EXISTS;


DROP TABLE TASK_MANAGER IF EXISTS;

CREATE TABLE TASK_MANAGER (
ID_TASK varchar(100), 
TITLE_CUSTOMER varchar(100), 
FIRSTNAME varchar(100), 
LASTNAME varchar(100) , 
NOTES varchar(100), 
SCHEDULETED_DATE varchar(20)
);

INSERT INTO TASK_MANAGER (ID_TASK, TITLE_CUSTOMER, FIRSTNAME, LASTNAME, NOTES, SCHEDULETED_DATE) VALUES('Mr.MAXSPO12091973','Mr.', 'MAX', 'SPO','','12091973');
INSERT INTO TASK_MANAGER (ID_TASK, TITLE_CUSTOMER, FIRSTNAME, LASTNAME, NOTES, SCHEDULETED_DATE) VALUES('Mr.MAXSPO12091975','Mr.', 'MAX', 'SPO','','12091975');
INSERT INTO TASK_MANAGER (ID_TASK, TITLE_CUSTOMER, FIRSTNAME, LASTNAME, NOTES, SCHEDULETED_DATE) VALUES('Mr.SPOSPO12091980','Mr.', 'SPO', 'SPO','','12091980');